### ISSUE TITLE
code

### ISSUE THREAD

**Issue by wuhucheng** [ggsDing/SCanNet#3]
I am very interested in your work on this paper.Can you share your code?

**Comment by ggsDing** [comment]
The codes are made available. Will be updated to optimize...

**Comment by ggsDing** [comment]
Hi,

Please find the updated repository<https://github.com/ggsDing/SCanNet/> with code and trained weights.

Best regards,
Lei Ding


发件人: ***@***.***>
发送时间: 2023年5月6日 15:24
收件人: ***@***.***>
抄送: ***@***.***>
主题: [ggsDing/SCanNet] code (Issue #3)


I am very interested in your work on this paper.Can you share your code?

―
