### ISSUE TITLE
Eval_SCD

### ISSUE THREAD

**Issue by sankarea-trh** [ggsDing/SCanNet#5]
Hi I am getting an error when evalthe predicted results using the SECOND dataset.
Traceback (most recent call last):
  File "Eval_SCD.py", line 127, in <module>
    Eval()
  File "Eval_SCD.py", line 86, in Eval
    assert unique_set.issubset(set([0, 1, 2, 3, 4, 5, 6])), "unrecognized label number"
AssertionError: unrecognized label number

The following is the same as my settings when predicting and evaluating
![q1](https://github.com/ggsDing/SCanNet/assets/77672105/41b00d71-8e6c-4d24-9845-7bf16cf5779d)
![q2](https://github.com/ggsDing/SCanNet/assets/77672105/f5c21be8-4ff3-4026-9cf4-79a392679c09)
Can you give me some help?

**Comment by ggsDing** [comment]
Hi,
The inference codes are provided for index predictions. From your codes, it seems that the inference path are for RGB predictions.
You can change the prediciton option 'index_map' in [pred_SCD.py](https://github.com/ggsDing/SCanNet/blob/main/pred_SCD.py) to output index predictions.
