### ISSUE TITLE
About the loss

### ISSUE THREAD

**Issue by TangYJ1229** [ggsDing/SCanNet#8]
In the paper, the loss is represented as follows, but the code includes an additional "loss_bn." I would like to inquire whether this "loss_bn" is encompassed within one of the existing losses.
![image](https://github.com/ggsDing/SCanNet/assets/79182380/48b1d090-b5d9-4b6f-abdb-43548985c5a5)
![image](https://github.com/ggsDing/SCanNet/assets/79182380/c8d3c545-0cd1-4722-9473-cf383178f896)

**Comment by ggsDing** [comment]
Hi, this is an omission that is fixed in the new version of the manuscript. The arxiv paper to be updated later.
